[theme]
primaryColor = "#2563EB"          # buttons, sliders, accents
backgroundColor = "#0B1220"       # page
secondaryBackgroundColor = "#111827"  # cards/sidebars
textColor = "#E5E7EB"             # text
font = "Inter"
